--- 
document: 
  name: "Manuale Tecnico per gli erogatori di servizi pubblici e privati"
  short_name: cie-manuale-tecnico
  description: "Manuale tecnico rivolto agli erogatori di servizio che fornisce una overview ad alto livello sulle modalità di funzionamento e integrazione dello schema di identificazione Entra con CIE per l'accesso ai servizi in rete di PP.AA e Privati."
  tags: 
    - Manuale tecnico
    - Entra con CIE
    - CIE
    - Carta di Identità Elettronica
    - Docs Italia
